/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"github.com/mokemoko/codebattle-core/server/models"
	"log"

	sw "codebattle/server/api/go"
	_ "github.com/mattn/go-sqlite3"
)

type Args struct {
	Port    string
	LogDir  string
	IsDebug bool
}

func parseArgs() Args {
	args := Args{}
	flag.StringVar(&args.Port, "port", "8080", "")
	flag.StringVar(&args.LogDir, "logDir", "./logs", "")
	flag.BoolVar(&args.IsDebug, "debug", false, "")
	flag.Parse()
	return args
}

func main() {
	args := parseArgs()

	if err := models.SetupDatabase(args.IsDebug); err != nil {
		log.Fatal(err)
	}

	router := sw.NewRouter()
	router.Static("/logs", args.LogDir)

	log.Printf("Server started")
	log.Fatal(router.Run(fmt.Sprintf(":%s", args.Port)))
}
