/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-sqlite3"
	"github.com/volatiletech/sqlboiler/v4/boil"

	sw "codebattle/server/api/go"
)

func setupDatabase() error {
	db, err := sql.Open("sqlite3", "../sql/db.sqlite3")
	if err != nil {
		return err
	}
	boil.DebugMode = true
	boil.SetDB(db)
	return nil
}

func main() {
	if err := setupDatabase(); err != nil {
		log.Fatal(err)
	}

	router := sw.NewRouter()

	log.Printf("Server started")
	log.Fatal(router.Run(":8080"))
}
