FROM golang:1.19 AS build
WORKDIR /go/src
COPY api .
COPY models ../models

# cgo required for go-sqlite3
ARG CGO_ENABLED=1
ARG GOOS=linux
ARG GOARCH=amd64

RUN go build -o api .

#FROM scratch AS runtime
FROM golang:1.19
WORKDIR /app
ENV GIN_MODE=release
COPY --from=build /go/src/api ./
EXPOSE 8080/tcp
ENTRYPOINT ["./api"]
