/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/mokemoko/codebattle-core/server/models"
	. "github.com/volatiletech/sqlboiler/v4/queries/qm"
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetMe -
func GetMe(c *gin.Context) {
	userId, _ := c.Get(userIdKey)

	user, err := models.Users(
		Where("id = ?", userId),
	).OneG(c)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err})
	} else {
		c.JSON(http.StatusOK, User{
			Id:   user.ID,
			Name: user.Name,
		})
	}
}
