/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetContests200ResponseInner struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
