/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PrivateEntryAllOf struct {

	Repository string `json:"repository"`

	Status string `json:"status"`

	Error string `json:"error,omitempty"`
}
