/*
 * CodeBattle API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MatchEntryAllOf struct {

	Rank int32 `json:"rank,omitempty"`

	BeforeScore int32 `json:"beforeScore,omitempty"`

	AfterScore int32 `json:"afterScore,omitempty"`
}
